language: c
sudo: required
dist: trusty
compiler: gcc
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.6'
addons:
  apt:
    packages:
    - libusb-1.0.0-dev
    - python-dev
    - python3-dev
install:
  - sudo python -m pip install -U pip scikit-build
before_script:
  - mkdir cmake-build
script:
  - cd cmake-build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - sudo env "PATH=$PATH" python setup.py install
  - cd ..
  - python -c 'import masterkeys'
